### PR TITLE
Add featured images to events

### PR DESCRIPTION
**Pull request by mashedkeyboard**
Hey, thanks for this plugin - it's great!

This PR adds support for featured images on events, in a very similar way to how it's implemented in Rainlab/Blog. The implementation I've put in the default component is very basic, fitting with the rest of the component, but this has some pretty obvious potential uses in lists of events or for social sharing cards in customised versions - hence I've included `featured_images` in the load for the other components too.

### CODE REVIEW

**Comment by nathanlesage** [comment]
This also looks fine from the logics of it – once you confirm that this works even in edge cases (no images, removing images, etc.) I'll gladly merge!

**Comment by mashedkeyboard** [comment]
Should work in either case, yep. The plugin doesn't actually handle the images at all, it's all dealt with through October's own stuff - it just fetches them if they exist, or, well, doesn't, if they don't 😄 The same is true in the admin for removing images - October deals with it entirely.

**Comment by nathanlesage** [comment]
Ah, after merging the last PR this one ended up conflicting; since I don't have time at my hands, would you mind double-checking and resolving the conflict? Then I can merge this one as well! Sorry for my long delay in answering you!

**Comment by nathanlesage** [comment]
Closing due to inactivity & in preparation for archiving.

**Pull request closed without merging**
